name: Generate build

on:
  pull_request: 
    branches: 
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Check commit patterns
      #   uses: wagoid/commitlint-github-action@v6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          # TODO REMOVER cache
          cache: npm
          cache-dependency-path: app/package-lock.json

      # - name: Install npm dependencies
      #   run: npm install

      # - name: Run lint
      #   run: npm run format

      # - name: Run tests
      #   run: npm test

      # - name: Setup EAS
      #   uses: expo/expo-github-action@v8
      #   with:
      #     eas-version: latest
      #     expo-version: latest
      #     token: ${{ secrets.EXPO_TOKEN }}

      - name: Extract expo.version
        id: extract_version
        run: |
          VERSION=$(node -e "console.log(require('./app/app.config.js').expo.version)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Show app version
        run: echo "$VERSION"
      
      # - name: Create preview
      #   run: |
      #     HEAD_REF="${{ github.event.pull_request.head.ref }}"
      #     BASE_REF="${{ github.event.pull_request.base.ref }}"
      #     MESSAGE="${HEAD_REF} <- ${BASE_REF}"
      #     eas update --auto --branch preview --message "$MESSAGE"

