name: PR Preview

on: [pull_request]

jobs:
  publish_preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: app/yarn.lock

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview comment
        uses: expo/expo-github-action/preview-comment@v8
        id: preview
        with:
          comment: true
          project: ./app
          channel: pr-${{ github.event.number }}

      - name: 💬 Comment in Slack
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: deployments
          slack-message: 'New deployment is ready!\n- Preview: ${{ steps.preview.outputs.projectQR }}'