name: PR Preview

on: [pull_request]

jobs:
  publish_preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: app/yarn.lock

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Publish preview
        run: eas update --branch preview --auto 

	  - name: Comment deployment link
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          msg: >
            You can [preview the PR here](${{ steps.preview.outputs.EXPO_QR_CODE_URL }}).<br><br>
            <a href="${{ steps.publish.outputs.EXPO_QR_CODE_URL }}"><img src="${{ steps.preview.outputs.EXPO_QR_CODE_URL }}" height="512px" width="512px"></a>
            <br><br>
            QR code not working or need a different client? Try the QR code or deep link from the [project page](${{steps.preview.outputs.EXPO_PROJECT_URL}}).
            <br><br>
            ${{ steps.publish.outputs.EXPO_NEW_BUILD_IS_REQUIRED_MESSAGE }}


      - name: Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          project: ./app
          channel: pr-${{ github.event.number }}